import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Link from "next/link";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
      <div className ="bg-slate-500 font-nano flex gap-10 p-10 text-white">
        
      <Link href="/Home">Home</Link>
      <Link href="/Aboutuskt">About uskt</Link>
      <Link href="/Admissions">Admissions</Link>
      <Link href="/Department">Department</Link>
     <Link href="/ContactUs">Contact Us</Link>
      </div>
        {children}

        <footer className="bg-gray-800 text-white py-6 mt-auto fixed bottom-0 left-0 w-full">
    <div className="container mx-auto px-4">
      <div className="flex flex-col md:flex-row justify-between items-center">
        {/* Left Section */}
        <div className="mb-7 md:mb-0">
          <h2 className="text-lg font-semibold">University of Sialkot</h2>
          <p className="text-sm">Created by Fiza Sarfraz All Rights are Reserved</p>
        </div>

        {/* Center Links */}
        <div className="flex space-x-4 mb-4 md:mb-0">
          <a href="#" className="hover:text-gray-400">Home</a>
          <a href="#" className="hover:text-gray-400">Admission</a>
          <a href="#" className="hover:text-gray-400">Departments</a>
          <a href="#" className="hover:text-gray-400">Contact</a>
        </div>

        {/* Right Links */}
        <div className="flex space-x-4">
          <a href="#" className="hover:text-gray-400">Privacy Policy</a>
          <a href="#" className="hover:text-gray-400">Terms of Service</a>
        </div>
      </div>
    </div>
  </footer>

</body>
</html>
  )
}